### ISSUE TITLE
Is there a single machine version?

### ISSUE THREAD

**Issue by ViGeng** [OpenGVLab/UniHCP#9]
Hi, amazing work!

Although not hopeful, I still want to ask:
Is there a single-machine version (no slurm) for some light use?

**Comment by orashi** [comment]
Thank you for your kind words and interest in our project!

Unfortunately as you said, we do not currently have a codebase that is not based on Slurm. 

However, you may be able to adapt the project for single-machine use by tweaking the launching bash script and the distributed utilities in our codebase. Particularly, you might want to look at the following lines in distributed_utils.py:
https://github.com/OpenGVLab/UniHCP/blob/37b93cd450aa423e580043012020a9af2b842e72/core/distributed_utils.py#L162-L195

I hope this helps, and feel free to ask if you have any other questions.

**Comment by ViGeng** [comment]
Thanks for your kind reply.
I will look into it :)

**Comment by mlnjeongpark** [comment]
I'm also looking forward to no slurm version. :)
Thanks for sharing great work!

**Comment by Jameschen7** [comment]
Here is my non-Slurm inference code for **human parsing** task in a forked repo: https://github.com/Jameschen7/UniHCP-inference.git.
